apiVersion: batch/v1
kind: Job
metadata:
  name: consumers
  labels:
    app: message-queue
    component: consumer
    chapter: jobs
spec:
  parallelism: 5
  template:
    metadata:
      labels:
        app: message-queue
        component: consumer
        chapter: jobs
    spec:
      containers:
      restartPolicy: OnFailure
        - image:  "gcr.io/kuar-demo/kuard-amd64:blue"
          name:  worker
          imagePullPolicy: Always
          args:
          - "--keygen-enable"
          - "--keygen-exit-on-complete"
          - "--keygen-memq-server=http://kuard.3b55544de056443fa2dc.uksouth.aksapp.io/a/memq/server"
          - "--keygen-memq-queue=keygen"
