apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: message-queue
    component: consumer
    chapter: jobs
  name: consumers
spec:
  parallelism: 5
  template:
    metadata:
      labels:
        app: message-queue
        component: consumer
        chapter: jobs
    spec:
      containers:
        - name:  worker
          image:  "gcr.io/kuar-demo/kuard-amd64:blue"
          imagePullPolicy: Always
          command: ["kuard",  "--keygen-enable","--keygen-memq-queue=keygen", "--keygen-exit-on-complete", "--keygen-memq-server=http://kuard.3b55544de056443fa2dc.uksouth.aksapp.io/a/memq/server"]
      restartPolicy: OnFailure
