apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuardpod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuardpod
  template:
    metadata:
      labels:
        app: kuardpod
    spec:
      volumes:
        - name: "kuard-data"
          hostPath:
            path:  "/var/lib/kuard"
      containers:
      - name: kuardpod
        image: gcr.io/kuar-demo/kuard-amd64:blue
        volumeMounts:
          - mountPath:  "/data"
            name:  "kuard-data"
        ports:
        - name:  http
          containerPort:  8080
          protocol: TCP
        resources:
          requests:
            cpu: "500m"
            memory: "128Mi"
          limits:
            cpu: "1000m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: kuardpod
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: kuardpod